version: "3"

volumes:
  local_postgres_data: {}

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ".env"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/postgres
    volumes:
      - .:/code:z
    expose:
      - 8000
    working_dir: /code
    command: |
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:12.9
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  web:
    image: nginx:1.21
    environment:
      - NGINX_PORT=80
      - SERVER_NAME=localhost
      - APP_HOST=app
      - APP_PORT=8000
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - app
