version: "3"

volumes:
  local_data: {}

services:
  postgres:
    image: postgres:12.9
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - local_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
